// A curated set of Lucide icons users can attach to a category. Named imports
// keep the bundle tree-shaken to just these. Ids are stable strings persisted on
// the category; keep them even if the picker order changes.

import {
  Film,
  Clapperboard,
  Video,
  Tv,
  Play,
  MonitorPlay,
  Popcorn,
  Music,
  Music2,
  Music4,
  Headphones,
  Mic,
  Radio,
  Disc3,
  Speaker,
  Podcast,
  AudioLines,
  ListMusic,
  Image,
  Images,
  Camera,
  Aperture,
  Palette,
  Brush,
  PenTool,
  FileText,
  File,
  Files,
  Newspaper,
  BookOpen,
  Book,
  Library,
  ScrollText,
  NotebookText,
  Receipt,
  FileSpreadsheet,
  Presentation,
  Archive,
  Package,
  Boxes,
  FolderArchive,
  Code,
  Terminal,
  FileCode,
  Braces,
  Binary,
  Bug,
  GitBranch,
  Database,
  Server,
  Cpu,
  Blocks,
  AppWindow,
  Download,
  CloudDownload,
  Puzzle,
  Wrench,
  Settings,
  Gamepad2,
  Joystick,
  Dices,
  Sword,
  Trophy,
  Ghost,
  Folder,
  FolderOpen,
  FolderHeart,
  Inbox,
  Star,
  Heart,
  Flag,
  Bookmark,
  Tag,
  Tags,
  Pin,
  Zap,
  Flame,
  Sparkles,
  Crown,
  Gem,
  Rocket,
  Globe,
  Cloud,
  Link,
  Paperclip,
  Bell,
  Calendar,
  Mail,
  MessageSquare,
  ShoppingCart,
  ShoppingBag,
  Briefcase,
  GraduationCap,
  Building,
  House,
  MapPin,
  Compass,
  Map,
  Car,
  Plane,
  Truck,
  Shield,
  Lock,
  Key,
  Fingerprint,
  Eye,
  Search,
  Filter,
  Layers,
  LayoutGrid,
  Shapes,
  Leaf,
  Trees,
  Sun,
  Moon,
  Droplet,
  Snowflake,
  Mountain,
  Feather,
  Bird,
  Cat,
  Dog,
  Fish,
  Flower,
  Apple,
  Coffee,
  Pizza,
  Utensils,
  Wine,
  Cake,
  IceCream,
  DollarSign,
  CreditCard,
  Wallet,
  Coins,
  PiggyBank,
  Banknote,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  createLucideIcon,
  type LucideIcon,
} from "lucide-react";

// A custom mark (three "X" strokes), supplied by the author. Built with Lucide's
// factory so it takes the same size/color props as the rest of the set — the svg
// wrapper (viewBox, currentColor stroke, round caps) comes from Lucide's default.
const Xxx = createLucideIcon("Xxx", [
  ["path", { d: "m10 8l4 8m-4 0l4-8m3 0l4 8m-4 0l4-8M3 8l4 8m-4 0l4-8", key: "xxx" }],
]);

// A filled document-with-download-arrow mark, supplied by the author. Unlike the
// stroke-drawn Lucide set, this one is a solid shape, so its path opts out of the
// factory's default `fill:none`/`stroke` and paints with `currentColor` instead —
// it still takes the same size/color props as every other icon.
const FileDown = createLucideIcon("FileDown", [
  [
    "path",
    {
      d: "M20 8.94a1.3 1.3 0 0 0-.06-.27v-.09a1 1 0 0 0-.19-.28l-6-6a1 1 0 0 0-.28-.19h-.1a1.1 1.1 0 0 0-.31-.11H7a3 3 0 0 0-3 3v14a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3zm-6-3.53L16.59 8H15a1 1 0 0 1-1-1ZM18 19a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h5v3a3 3 0 0 0 3 3h3Zm-4.71-4.71l-.29.3V12a1 1 0 0 0-2 0v2.59l-.29-.3a1 1 0 0 0-1.42 1.42l2 2a1 1 0 0 0 .33.21a.94.94 0 0 0 .76 0a1 1 0 0 0 .33-.21l2-2a1 1 0 0 0-1.42-1.42",
      fill: "currentColor",
      stroke: "none",
      key: "file-down",
    },
  ],
]);

/** Ordered list for the picker grid: `[id, component]`. */
export const CATEGORY_ICONS: readonly (readonly [string, LucideIcon])[] = [
  ["film", Film],
  ["clapperboard", Clapperboard],
  ["video", Video],
  ["tv", Tv],
  ["play", Play],
  ["monitor-play", MonitorPlay],
  ["popcorn", Popcorn],
  ["music", Music],
  ["music-2", Music2],
  ["music-4", Music4],
  ["headphones", Headphones],
  ["mic", Mic],
  ["radio", Radio],
  ["disc-3", Disc3],
  ["speaker", Speaker],
  ["podcast", Podcast],
  ["audio-lines", AudioLines],
  ["list-music", ListMusic],
  ["image", Image],
  ["images", Images],
  ["camera", Camera],
  ["aperture", Aperture],
  ["palette", Palette],
  ["brush", Brush],
  ["pen-tool", PenTool],
  ["file-text", FileText],
  ["file", File],
  ["files", Files],
  ["file-down", FileDown],
  ["newspaper", Newspaper],
  ["book-open", BookOpen],
  ["book", Book],
  ["library", Library],
  ["scroll-text", ScrollText],
  ["notebook-text", NotebookText],
  ["receipt", Receipt],
  ["file-spreadsheet", FileSpreadsheet],
  ["presentation", Presentation],
  ["archive", Archive],
  ["package", Package],
  ["boxes", Boxes],
  ["folder-archive", FolderArchive],
  ["code", Code],
  ["terminal", Terminal],
  ["file-code", FileCode],
  ["braces", Braces],
  ["binary", Binary],
  ["bug", Bug],
  ["git-branch", GitBranch],
  ["database", Database],
  ["server", Server],
  ["cpu", Cpu],
  ["blocks", Blocks],
  ["app-window", AppWindow],
  ["download", Download],
  ["cloud-download", CloudDownload],
  ["puzzle", Puzzle],
  ["wrench", Wrench],
  ["settings", Settings],
  ["gamepad-2", Gamepad2],
  ["joystick", Joystick],
  ["dices", Dices],
  ["sword", Sword],
  ["trophy", Trophy],
  ["ghost", Ghost],
  ["folder", Folder],
  ["folder-open", FolderOpen],
  ["folder-heart", FolderHeart],
  ["inbox", Inbox],
  ["star", Star],
  ["heart", Heart],
  ["flag", Flag],
  ["bookmark", Bookmark],
  ["tag", Tag],
  ["tags", Tags],
  ["pin", Pin],
  ["zap", Zap],
  ["flame", Flame],
  ["sparkles", Sparkles],
  ["crown", Crown],
  ["gem", Gem],
  ["rocket", Rocket],
  ["globe", Globe],
  ["cloud", Cloud],
  ["link", Link],
  ["paperclip", Paperclip],
  ["bell", Bell],
  ["calendar", Calendar],
  ["mail", Mail],
  ["message-square", MessageSquare],
  ["shopping-cart", ShoppingCart],
  ["shopping-bag", ShoppingBag],
  ["briefcase", Briefcase],
  ["graduation-cap", GraduationCap],
  ["building", Building],
  ["house", House],
  ["map-pin", MapPin],
  ["compass", Compass],
  ["map", Map],
  ["car", Car],
  ["plane", Plane],
  ["truck", Truck],
  ["shield", Shield],
  ["lock", Lock],
  ["key", Key],
  ["fingerprint", Fingerprint],
  ["eye", Eye],
  ["search", Search],
  ["filter", Filter],
  ["layers", Layers],
  ["layout-grid", LayoutGrid],
  ["shapes", Shapes],
  ["leaf", Leaf],
  ["trees", Trees],
  ["sun", Sun],
  ["moon", Moon],
  ["droplet", Droplet],
  ["snowflake", Snowflake],
  ["mountain", Mountain],
  ["feather", Feather],
  ["bird", Bird],
  ["cat", Cat],
  ["dog", Dog],
  ["fish", Fish],
  ["flower", Flower],
  ["apple", Apple],
  ["coffee", Coffee],
  ["pizza", Pizza],
  ["utensils", Utensils],
  ["wine", Wine],
  ["cake", Cake],
  ["ice-cream", IceCream],
  ["dollar-sign", DollarSign],
  ["credit-card", CreditCard],
  ["wallet", Wallet],
  ["coins", Coins],
  ["piggy-bank", PiggyBank],
  ["banknote", Banknote],
  ["trending-up", TrendingUp],
  ["bar-chart", BarChart3],
  ["pie-chart", PieChart],
  ["activity", Activity],
  ["xxx", Xxx],
];

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(CATEGORY_ICONS);

/** The Lucide component for an icon id, or null when unknown/absent. */
export function categoryIcon(id: string | null): LucideIcon | null {
  return id ? ICON_MAP[id] ?? null : null;
}
